name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🎮 Generate Pacman Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: MohGhazy
          outputs: |
            output/pacman-contribution-graph.svg?palette=github&color_snake=#39FF14&color_dots=#39FF14,#2ECC71,#27AE60,#1E8449,#145A32
            output/pacman-contribution-graph-dark.svg?palette=github-dark&background=transparent&color_snake=#39FF14

      - name: 🚀 Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          force_orphan: true
